In [2]:
import sqlite3 as sq
import pandas as pd

In [3]:
df = pd.read_csv("chicago_crime_2025.csv")
df.head()
df.columns

Index(['id', 'case_number', 'date', 'block', 'iucr', 'primary_type',
       'description', 'location_description', 'arrest', 'domestic', 'beat',
       'district', 'ward', 'community_area', 'fbi_code', 'x_coordinate',
       'y_coordinate', 'year', 'updated_on', 'latitude', 'longitude',
       'location'],
      dtype='str')

In [4]:
crime = pd.read_csv("chicago_crime_2025.csv")
conn = sq.connect("crime.db")

In [5]:
crime.to_sql("chicago_crime_2025",conn,if_exists="replace",index=False)

236633

In [6]:
query = """SELECT * FROM chicago_crime_2025 LIMIT 5;"""

output = pd.read_sql(query, conn) 
output

,id,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
0,14024965,JJ484232,2025-01-01T00:00:00.000,007XX S INDEPENDENCE BLVD,1562,SEX OFFENSE,AGGRAVATED CRIMINAL SEXUAL ABUSE,RESIDENCE,0,0,...,24.0,27.0,17,1151379.0,1896339.0,2025,2025-11-12T15:45:20.000,41.871437,-87.719700,"{'latitude': '41.871436933', 'longitude': '-87..."
1,14034324,JJ443201,2025-01-01T00:00:00.000,026XX S RIDGEWAY AVE,1562,SEX OFFENSE,AGGRAVATED CRIMINAL SEXUAL ABUSE,RESIDENCE,0,0,...,22.0,30.0,17,1151797.0,1886181.0,2025,2025-11-22T15:41:52.000,41.843554,-87.718433,"{'latitude': '41.84355397', 'longitude': '-87...."
2,14035171,JJ496186,2025-01-01T00:00:00.000,081XX S CALIFORNIA AVE,1562,SEX OFFENSE,AGGRAVATED CRIMINAL SEXUAL ABUSE,SCHOOL - PUBLIC BUILDING,0,0,...,18.0,70.0,17,1159127.0,1850529.0,2025,2025-11-23T15:41:46.000,41.745573,-87.692508,"{'latitude': '41.745572921', 'longitude': '-87..."
3,14045279,JJ508875,2025-01-01T00:00:00.000,080XX S MARYLAND AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,0,0,...,8.0,44.0,11,1183298.0,1851901.0,2025,2025-12-05T15:52:17.000,41.748810,-87.603899,"{'latitude': '41.748809737', 'longitude': '-87..."
4,14047551,JJ512119,2025-01-01T00:00:00.000,013XX W 97TH PL,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,0,0,...,21.0,73.0,14,1169144.0,1840175.0,2025,2025-12-07T15:41:23.000,41.716949,-87.656102,"{'latitude': '41.71694947', 'longitude': '-87...."

In [9]:
query = """SELECT district, description, count(*) FROM chicago_crime_2025 GROUP BY district ORDER BY district;"""

output = pd.read_sql(query, conn) 
output

    district                                        description  count(*)
0          1                                         TO VEHICLE     13670
1          2                FINANCIAL IDENTITY THEFT OVER $ 300     12680
2          3                FINANCIAL IDENTITY THEFT OVER $ 300     12710
3          4                                   TELEPHONE THREAT     13063
4          5                                         TO VEHICLE      9272
5          6                FINANCIAL IDENTITY THEFT OVER $ 300     13557
6          7                                        TO PROPERTY     10105
7          8                   AGGRAVATED CRIMINAL SEXUAL ABUSE     15197
8          9                FINANCIAL IDENTITY THEFT OVER $ 300     10464
9         10                   AGGRAVATED CRIMINAL SEXUAL ABUSE      9497
10        11                   AGGRAVATED CRIMINAL SEXUAL ABUSE     12926
11        12  AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER     14882
12        14                FINANCIAL IDENTITY THEFT OVER $ 300      8015
13        15                                          OVER $500      7812
14        16                                             SIMPLE      8069
15        17                         RECKLESS FIREARM DISCHARGE      7289
16        18                FINANCIAL IDENTITY THEFT OVER $ 300     13188
17        19                           FRAUD OR CONFIDENCE GAME     12499
18        20                FINANCIAL IDENTITY THEFT OVER $ 300      4984
19        22                                        TO PROPERTY      7614
20        24                FINANCIAL IDENTITY THEFT OVER $ 300      7594
21        25                FINANCIAL IDENTITY THEFT OVER $ 300     11534
22        31                                         TO VEHICLE        12

In [10]:
query = """
SELECT
    district,
    year,
    COUNT(*) AS n_crimes,
    -- window function: percent of total crimes per district
    1.0 * COUNT(*) / SUM(COUNT(*)) OVER (PARTITION BY district) AS pct_of_district
FROM chicago_crime_2025
GROUP BY district, year
ORDER BY district, year;
"""

output = pd.read_sql(query, conn) 
output

    district  year  n_crimes  pct_of_district
0          1  2025     13670              1.0
1          2  2025     12680              1.0
2          3  2025     12710              1.0
3          4  2025     13063              1.0
4          5  2025      9272              1.0
5          6  2025     13557              1.0
6          7  2025     10105              1.0
7          8  2025     15197              1.0
8          9  2025     10464              1.0
9         10  2025      9497              1.0
10        11  2025     12926              1.0
11        12  2025     14882              1.0
12        14  2025      8015              1.0
13        15  2025      7812              1.0
14        16  2025      8069              1.0
15        17  2025      7289              1.0
16        18  2025     13188              1.0
17        19  2025     12499              1.0
18        20  2025      4984              1.0
19        22  2025      7614              1.0
20        24  2025      7594              1.0
21        25  2025     11534              1.0
22        31  2025        12              1.0